# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eRKGaT144j5SYVM7wmw0CA04u2oZVxCu
"""

print('##  Program Python Deret Angka Ganjil  ##')
print('========================================')
print()

awal = int(input('Input Angka: '))
 
for i in range(awal, 0, -1):
  if (i % 2 != 0):
    print(i, end=" ")